import { type Knex } from 'knex';

export const up = (knex: Knex) =>
  knex.schema.raw(`do $$begin

    create table documents (
      id           integer generated by default as identity primary key,
      uid          uuid default gen_random_uuid() not null,
      created_at   timestamptz not null default now(),
      updated_at   timestamptz not null default now(),
      user_id      uuid not null,
      title        text not null default '',
      slug         text not null default '',
      body         text not null default '',
      parent_id    uuid references documents(uid) on delete set null,
      is_published boolean not null default true,
      visibility   text not null default 'public'
        check (visibility in ('public', 'protected', 'private'))
    );

    create unique index documents_uid_idx on documents (uid);
    create index documents_user_id_idx on documents (user_id);
    create index documents_parent_id_idx on documents (parent_id);

    -- Per-user unique slug (empty = draft, not constrained)
    create unique index documents_user_slug_idx on documents (user_id, slug)
      where slug <> '';

    create table document_tags (
      document_id uuid not null references documents(uid) on delete cascade,
      tag         text not null,
      primary key (document_id, tag)
    );

    create index document_tags_tag_idx on document_tags (tag);

    -- Auto-update updated_at on document change
    create function trg_documents_updated_at() returns trigger as
    $BODY$
    begin
      new.updated_at = now();
      return new;
    end;
    $BODY$
    language plpgsql;

    create trigger trg_documents_updated_at
      before update on documents
      for each row execute function trg_documents_updated_at();

  end$$`);

export const down = (knex: Knex) =>
  knex.schema.raw(`do $$begin
    drop trigger trg_documents_updated_at on documents;
    drop function trg_documents_updated_at();
    drop table document_tags;
    drop table documents;
  end$$`);